# Generated by Django 3.1 on 2020-08-28 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_user',
            name='DOB',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='app_user',
            name='Fname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='app_user',
            name='Lname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='app_user',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True),
        ),
    ]
