# Generated by Django 3.1 on 2020-08-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_task', '0002_auto_20200828_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='app_user',
            name='DOB',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='app_user',
            name='Fname',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='app_user',
            name='Lname',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='app_user',
            name='gender',
            field=models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='app_user',
            name='pic',
            field=models.ImageField(blank=True, default='', null=True, upload_to='pics'),
        ),
    ]
