# Generated by Django 3.1.1 on 2020-10-05 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_task', '0006_chat_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_model',
            name='file',
            field=models.FileField(blank=True, default='', null=True, upload_to='files'),
        ),
    ]
