# Generated by Django 3.1.1 on 2020-10-05 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CRUD_task', '0007_chat_model_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mail_model',
            name='chat',
        ),
    ]
